config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :microposts do
    member do
      post 'retweet'
      patch 'favorite'
      patch 'unfavorite'
    end
  end
  
  resources :users do
    # users/1/following_users
    # users/1/follower_users
    member do
      get 'following_users'
      get 'follower_users'
      get 'favorites'
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  get 'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: "static_pages#home"
end

app/models/user.rb
class User < ActiveRecord::Base
    before_save { self.email = self.email.downcase }
    #name require, max50
    validates :name, presence: true, length: { maximum: 50 }
    #email require, max 255, formatmail
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: { case_sensitive: false }
    #更新時にはhas_secure_passwordはパスワードが無くても更新出来るようになっているっぽい
    validates :password, length: { minimum: 6 }, allow_nil: true
    validates :description, length: { maximum: 255 }
    has_secure_password
    has_many :microposts
    
    has_many :likes, dependent: :destroy
    has_many :like_posts, through: :likes, source: :issueable, source_type: 'Micropost'

    # has_many :throughの関連に同一モデルを含む場合
    # User > RelationShip > User
    # RelationShipが2つのUserと関連づけられているが、外部キーをどう指定するか

    # A.外部キーをそれぞれ別に持たせ,class_name=>:クラス名とする
    # has_manyの第一引数でフォローしている人,フォローされている人で別々で扱える
    has_many :following_relationships, :class_name => "Relationship", :foreign_key => "follower_id", dependent: :destroy
    has_many :follower_relationships, :class_name => "Relationship", :foreign_key => "followed_id", dependent: :destroy
    
    # RelationShipを通して2つのUserを相互に関連付けるには？
    # A.:through =>:中間クラス名と:source=>:中間クラスを通して参照する参照名(belongs_toで自由につけられる。その場合は外部キーを自分で指定する)
    has_many :following_users, :through => :following_relationships, :source => :followed_user
    has_many :follower_users, :through => :follower_relationships, :source => :follower_user
    
    def follow(other_user)
        #現在のユーザーが指定ユーザーをフォローしていない場合はフォロー
        following_relationships.find_or_create_by(followed_id: other_user.id)
    end
    
    def unfollow(other_user)
        #現在のユーザーがフォローしているユーザーから指定ユーザーをアンフォロー
        following_relationship = following_relationships.find_by(followed_id: other_user.id)
        following_relationship.destroy if following_relationship
    end
    
    #あるユーザーをフォローしているかどうか
    def following?(other_user)
        following_users.include?(other_user)
    end
    
    #自分とフォローしているユーザーの投稿を取得する
    def feed_items
        Micropost.where(user_id: following_user_ids + [self.id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  #ログインしていない場合はリダイレクト
  before_action :redirect_unlogged_user, only: [:show, :edit, :update]
  #自分以外のユーザーが編集できないようにする
  before_action :forbid_other_user_edit, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(params[:id])
    # @microposts = @user.microposts.order(created_at: :desc)
    @microposts = @user.microposts.page(params[:page]).order(created_at: :desc)
  end
  
  def favorites
    @user = User.find(params[:id])
    @favorites = @user.like_posts.page(params[:page]).order(created_at: :desc)
    render 'show'
  end
  
  def following_users
    @user = User.find(params[:id])
    @following_users = @user.following_users.page(params[:page]).per(5)
    #showと同じテンプレートを返す
    render 'show'
  end
  
  def follower_users
    @user = User.find(params[:id])
    @follower_users = @user.follower_users.page(params[:page]).per(5)
    render 'show'
  end
  
  def edit
  end
  
  def update
    if @user.update(update_params)
      flash[:success] = '更新しました'
      redirect_to edit_user_path(@user)
    else
      flash[:danger] = '更新に失敗しました'
      render 'edit'
    end
  end
  
  #ユーザー新規登録
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = 'ユーザー登録しました'
      redirect_to @user
    else
      #バリデーション結果のuserオブジェクトをそのままnewを出す
      render 'new'
    end
  end
  
  private
    def set_user
      @user = User.find(params[:id])
    end

    def redirect_unlogged_user
      unless logged_in?
        redirect_to root_path
      end
    end
    
    def forbid_other_user_edit
      if current_user != @user
        redirect_to root_path
      end
    end

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
    
    def update_params
      params.require(:user).permit(:name, :email, :description, :password, :password_confirmation)
    end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
    <div>
        <%= hidden_field_tag :followed_id, @user.id %>
    </div>
    
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
    <div id="follow_form">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow' %>
        <% else %>
            <%= render 'follow' %>
        <% end %>
    </div>
<% end %>

app/views/users/_follow_users.erb
<% # 初回はfollow_userがあるが、ajax時にかえってきてない %>
<li id="follow-users-<%= follow_user.id %>">
  <%= link_to gravatar_for(follow_user, size: 50), follow_user %>
  <span class="user"><%= link_to follow_user.name, follow_user %></span>
</li>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
        html: { method: :delete },
        remote: true) do |f| %>
    
<%= f.submit "Unfollow", class: "btn" %>

<% end %>

app/views/users/_user.html.erb
<li id="user-<%= user.id %>">
  <%= link_to gravatar_for(user, size: 50), user %>
  <span class="user"><%= link_to user.name, user %></span>
</li>

app/views/users/edit.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: user_path, method: :patch) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name, value: "名前" %>
      <%= f.text_field :name, class: "form-control" %>
    
      <%= f.label :email, value: "メールアドレス" %>
      <%= f.email_field :email, class: "form-control" %>

      <%= f.label :description, value: "自己紹介" %>
      <%= f.text_area :description, class: "form-control", maxlength: 255, rows: "4" %>
      
      <%= f.submit "プロフィールを更新する", class: "btn btn-primary" %>
    <% end %>
    
    <div class="mt-10">
      <% # パスワードを入力しなくてもプロフィールを変更できることを明示するためにフォームを分けた %>
      <%= form_for(@user, url: user_path, method: :patch) do |f| %>
        <%= f.label :password, value: "パスワード" %>
        <%= f.password_field :password, class: "form-control", required: "required" %>
        
        <%= f.label :password_confirmation, value: "確認用パスワード" %>
        <%= f.password_field :password_confirmation, class: "form-control", required: "required" %>
        
        <%= f.submit "パスワードを更新する", class: "btn btn-success" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
        
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control" %>
            
            <%= f.label :email %>
            <%= f.email_field :email, class: "form-control" %>
            
            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>
            <%= f.submit "Create My Account", class: "btn btn-large btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <ul class="follow-list">
        <li><%= link_to "ツイート", user_path(@user) %></li>
        <li><%= link_to "フォロー", following_users_user_path(@user) %></li>
        <li><%= link_to "フォロワー", follower_users_user_path(@user) %></li>
        <li><%= link_to "お気に入りツイート", favorites_user_path(@user) %></li>
      </ul>
      <p><%= @user.description %></p>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>

    <% if params[:action] == 'show' %>
      <h3>ツイート</h3>
      <% if @user.microposts.any? %>
        <ol class="microposts">
          <% # 別フォルダの部分テンプレートを参照 %>
          <% # collectionのモデルの内容をみて部分テンプレートに展開される %>
          <%= render @microposts %>
          <%= paginate @microposts %>
        </ol>
      <% else %>
        <p>まだツイートがありません</p>
      <% end %>
    <% elsif params[:action] == 'following_users' %>
      <h3>フォロー中のユーザー</h3>
      <% if @following_users.any? %>
        <ol class="users">
          <% # モデルの中身で参照する。users/_user.html.erbが参照される。変数名は関係なし %>
          <%= render @following_users %>
          <%= paginate @following_users %>
        </ol>
      <% else %>
        <p>まだフォロー中のユーザーはいません</p>
      <% end %>
    <% elsif params[:action] == 'favorites' %>
      <h3>お気に入りツイート一覧</h3>
      <% if @favorites.any? %>
        <ol class="microposts">
          <%= render @favorites %>
          <%= paginate @favorites %>
        </ol>
      <% else %>
        <p>まだフォロー中のユーザーはいません</p>
      <% end %>
    <% else %>
      <h3>フォローされているユーザー</h3>
      <% if @follower_users.any? %>
        <ol class="users">
          <%= render @follower_users %>
          <%= paginate @follower_users %>
        </ol>
      <% else %>
        <p>まだフォローされているのユーザーはいません</p>
      <% end %>
    <% end %>
</div>