config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  resources :microposts do
    member do
      post 'retweet'
      patch 'favorite'
      patch 'unfavorite'
    end
  end
  
  resources :users do
    # users/1/following_users
    # users/1/follower_users
    member do
      get 'following_users'
      get 'follower_users'
      get 'favorites'
    end
  end
  
  resources :relationships, only: [:create, :destroy]
  
  get 'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  root to: "static_pages#home"
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to t('navigation.home'), root_path %></li>
        <li><%= link_to t('navigation.help'), '#' %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= t('navigation.account') %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to t('navigation.profile'), current_user %>
              </li>
              <li>
                <% # インスタンス変数(@user)だと初期化していないアクションだとエラーになるのでsessionヘルパーでどこからでも使えるようにする %>
                <%= link_to t('navigation.setting'), edit_user_path(current_user.id) %>
              </li>
              <li class="divider"></li>
              <li>
                <%= link_to t('navigation.logout'), logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li>
            <%= link_to "login", login_path %>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
  </div>
</body>
</html>